pipeline{
    agent any
    stages{
        stage("build stage"){
            steps{
                sh "cd sonarqube-scanner-maven/maven-basic ; mvn install"
            }
        }
        stage("test"){
            steps{
                sh "cd sonarqube-scanner-maven/maven-basic ; mvn test"
            }
        }
        stage("sonarcube anyalsis"){
            environment{
                def scannerHome = tool 'sonarQubescanner'
            }
            steps {
                withSonarQubeEnv('sonarserver 9.5') {
                sh "mvn clean verify sonar:sonar \
                        -Dsonar.projectKey=hello \
                        -Dsonar.host.url=http://3.93.178.168:8082 \
                        -Dsonar.login=sqp_21b802691e9d386ccb6c83c5a861ae1684564cb2"
                }
            }
        }
    }
}