pipeline{
    agent any
    stages{
        stage("build stage"){
            steps{
                sh "cd sonarqube-scanner-maven/maven-basic ; mvn install"
            }
        }
        stage("test"){
            steps{
                sh "cd sonarqube-scanner-maven/maven-basic ; mvn test"
            }
        }
        stage("sonarcube anyalsis"){
            environment{
                def scannerHome = tool 'sonarQubescanner'
            }
            steps {
                withSonarQubeEnv('sonarserver 9.5') {
                sh "mvn clean verify sonar:sonar \
                    -Dsonar.projectKey=siva \
                    -Dsonar.host.url=http://3.93.178.168:8082 \
                    -Dsonar.login=sqp_79338d7620aa08df8af54066309a2cb0062c363e"
                }
            }
        }
    }
}