pipeline{
    agent any
    stages{   
        stage("build stage"){
            steps{
                sh "cd sonar-scanning-examples/sonarqube-scanner-maven/maven-basic/git;mvn clean install"
            }
        }
    }
}